nmovalle/TheCollabSys.Backend.API

TheCollabSys.Backend.API/Configuration/AutenticationServiceIstaller.cs, TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Configuration/PresentationServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/AuthController.cs, TheCollabSys.Backend.API/Controllers/ClientsController.cs, TheCollabSys.Backend.API/Controllers/DomainController.cs, TheCollabSys.Backend.API/Controllers/TokenController.cs, TheCollabSys.Backend.API/OptionSetup/JwtBearerOptionsSetup.cs, TheCollabSys.Backend.API/OptionSetup/JwtOptions.cs, TheCollabSys.Backend.API/OptionSetup/JwtOptionsSetup.cs, TheCollabSys.Backend.API/Program.cs, TheCollabSys.Backend.API/Token/IJwtTokenGenerator.cs, TheCollabSys.Backend.API/Token/JwtTokenGenerator.cs, TheCollabSys.Backend.API/appsettings.json, TheCollabSys.Backend.Data/Interfaces/ITokenRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/TokenRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/Models/Token.cs, TheCollabSys.Backend.Services/ITokenService.cs, TheCollabSys.Backend.Services/TokenService.cs
- Se agrega Generación de JWT Token
=> TheCollabsys: Se agrega Generación de JWT Token

TheCollabSys.Backend.API/Configuration/RepositoryServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/UserController.cs, TheCollabSys.Backend.API/TheCollabSys.Backend.API.csproj, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Interfaces/IUserRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/UserRepository.cs, TheCollabSys.Backend.Data/TheCollabSys.Backend.Data.csproj, TheCollabSys.Backend.Entity/DTOs/UserDTO.cs, TheCollabSys.Backend.Entity/Models/ApplicationUser.cs, TheCollabSys.Backend.Entity/Models/UserCreationModel.cs, TheCollabSys.Backend.Entity/TheCollabSys.Backend.Entity.csproj, TheCollabSys.Backend.Services/IUserService.cs, TheCollabSys.Backend.Services/UserService.cs
- Se agrega funcionalidad para registro de usuarios y autenticacion por credenciales
=> The Collabsys - login credentials

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/BaseController.cs, TheCollabSys.Backend.API/Controllers/ClientsController.cs, TheCollabSys.Backend.API/Controllers/EmployersController.cs, TheCollabSys.Backend.Data/Interfaces/IEmployerRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/EmployerRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/EmployerDTO.cs, TheCollabSys.Backend.Entity/Models/DdEmployer.cs, TheCollabSys.Backend.Services/ClientService.cs, TheCollabSys.Backend.Services/EmployerService.cs, TheCollabSys.Backend.Services/IEmployerService.cs, TheCollabSys.Backend.Services/MappingProfile.cs
employers crud methods were created
=> employers crud methods were created

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/SkillsController.cs, TheCollabSys.Backend.Data/Interfaces/ISkillRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/SkillRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/SkillDTO.cs, TheCollabSys.Backend.Services/ISkillService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/SkillService.cs
=> The Collabsys: crud for skills entity

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/ProjectsController.cs, TheCollabSys.Backend.Data/Interfaces/IProjectRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/ProjectRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/ProjectDTO.cs, TheCollabSys.Backend.Entity/Models/DdProject.cs, TheCollabSys.Backend.Services/IProjectService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/ProjectService.cs
=> The Collabsys: crud for projects entity

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/ClientsController.cs, TheCollabSys.Backend.API/Controllers/EmployersController.cs, TheCollabSys.Backend.API/Controllers/EngineersController.cs, TheCollabSys.Backend.API/Controllers/SkillsController.cs, TheCollabSys.Backend.Data/Interfaces/IEngineerRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/EngineerRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/EngineerDTO.cs, TheCollabSys.Backend.Entity/Models/DdEngineer.cs, TheCollabSys.Backend.Services/EngineerService.cs, TheCollabSys.Backend.Services/IEngineerService.cs, TheCollabSys.Backend.Services/MappingProfile.cs
=> The Collabsys - Engineers Entity

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/EngineerSkillsController.cs, TheCollabSys.Backend.Data/Interfaces/IEngineerSkillRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/EngineerSkillRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/EngineerSkillDTO.cs, TheCollabSys.Backend.Entity/DTOs/EngineerSkillDetailDTO.cs, TheCollabSys.Backend.Services/EngineerSkillService.cs, TheCollabSys.Backend.Services/IEngineerSkillService.cs, TheCollabSys.Backend.Services/MappingProfile.cs
=> The Collabsys - Engineers Skills

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/SkillCategoriesController.cs, TheCollabSys.Backend.API/TheCollabSys.Backend.API.csproj, TheCollabSys.Backend.Data/Interfaces/ISkillCategoryRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/SkillCategoryRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/SkillCategoryDTO.cs, TheCollabSys.Backend.Entity/Models/DdSkill.cs, TheCollabSys.Backend.Entity/Models/DdSkillCategory.cs, TheCollabSys.Backend.Entity/Models/DdSkillSubcategory.cs, TheCollabSys.Backend.Services/ISkillCategoryService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/ProjectService.cs, TheCollabSys.Backend.Services/SkillCategoryService.cs
=> The Collabsys - Skills Categories

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/SkillSubcategoriesController.cs, TheCollabSys.Backend.Data/Interfaces/ISkillSubcategoryRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/SkillSubcategoryRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Entity/DTOs/SkillDTO.cs, TheCollabSys.Backend.Entity/DTOs/SkillSubcategoryDTO.cs, TheCollabSys.Backend.Services/ISkillSubcategoryService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/SkillService.cs, TheCollabSys.Backend.Services/SkillSubcategoryService.cs
=> The Collabsys - Skills Subcategories CRUD

TheCollabSys.Backend.Entity/DTOs/EngineerSkillDetailDTO.cs, TheCollabSys.Backend.Services/EngineerSkillService.cs
=> The Collabsys - Add Columns

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/AuthController.cs, TheCollabSys.Backend.API/Controllers/MenuRolesController.cs, TheCollabSys.Backend.Data/Interfaces/IMenuRepository.cs, TheCollabSys.Backend.Data/Interfaces/IMenuRolesRepository.cs, TheCollabSys.Backend.Data/Interfaces/ISubMenuRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/MenuRepository.cs, TheCollabSys.Backend.Data/Repositories/MenuRolesRepository.cs, TheCollabSys.Backend.Data/Repositories/SubMenuRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/MenuRoleDetailDTO.cs, TheCollabSys.Backend.Entity/Models/AspNetRole.cs, TheCollabSys.Backend.Entity/Models/DdMenu.cs, TheCollabSys.Backend.Entity/Models/DdMenuRole.cs, TheCollabSys.Backend.Entity/Models/DdSubMenu.cs, TheCollabSys.Backend.Services/IMenuRolesService.cs, TheCollabSys.Backend.Services/MenuRolesService.cs
=> The Collabsys - Menu Roles and Submenus

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/MenuController.cs, TheCollabSys.Backend.API/Controllers/SubMenuController.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/MenuDTO.cs, TheCollabSys.Backend.Entity/DTOs/MenuRoleDTO.cs, TheCollabSys.Backend.Entity/DTOs/SubMenuDTO.cs, TheCollabSys.Backend.Services/IMenuRolesService.cs, TheCollabSys.Backend.Services/IMenuService.cs, TheCollabSys.Backend.Services/ISubMenuService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/MenuRolesService.cs, TheCollabSys.Backend.Services/MenuService.cs, TheCollabSys.Backend.Services/SubMenuService.cs
=> The Collabsys - Manage Menus CRUD

TheCollabSys.Backend.API/Configuration/AutenticationServiceIstaller.cs, TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/AuthController.cs, TheCollabSys.Backend.API/Controllers/TokenController.cs, TheCollabSys.Backend.API/Token/IJwtTokenGenerator.cs, TheCollabSys.Backend.API/Token/JwtTokenGenerator.cs, TheCollabSys.Backend.Data/Interfaces/ITokenRepository.cs, TheCollabSys.Backend.Data/Repositories/TokenRepository.cs, TheCollabSys.Backend.Entity/DTOs/AspNetUserTokensDTO.cs, TheCollabSys.Backend.Entity/Request/AuhenticationRefreshRequestBody.cs, TheCollabSys.Backend.Entity/Request/RefreshRequest.cs, TheCollabSys.Backend.Services/ITokenService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/TokenService.cs
=> The Collabsys - Refresh Token based on access token

TheCollabSys.Backend.Entity/DTOs/EngineerDTO.cs, TheCollabSys.Backend.Entity/DTOs/ProjectAssignmentDetailDTO.cs, TheCollabSys.Backend.Services/EngineerService.cs, TheCollabSys.Backend.Services/EngineerSkillService.cs, TheCollabSys.Backend.Services/ProjectAssignmentService.cs
=> The Collabsys - Engineers and Assignments include rating

TheCollabSys.Backend.API/Controllers/ProjectsController.cs, TheCollabSys.Backend.Services/IProjectService.cs, TheCollabSys.Backend.Services/ProjectService.cs, TheCollabSys.Backend.Services/TheCollabSys.Backend.Services.csproj
=> The Collabsys - Dasboard kpis

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/EmployerProjectAssignmentController.cs, TheCollabSys.Backend.Data/Interfaces/IEmployerProjectAssignmentRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/EmployerProjectAssignmentRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/EmployerProjectAssignmentDetailDTO.cs, TheCollabSys.Backend.Entity/Models/DdEmployer.cs, TheCollabSys.Backend.Entity/Models/DdEmployerProjectAssignment.cs, TheCollabSys.Backend.Entity/Models/DdProject.cs, TheCollabSys.Backend.Services/EmployerProjectAssignmentService.cs, TheCollabSys.Backend.Services/IEmployerProjectAssignmentService.cs
=> The Collabsys - employer project assignment feature

TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/Models/AspNetUser.cs, TheCollabSys.Backend.Entity/Models/DdProject.cs
=> The Collabsys - relation between project and client fixed

TheCollabSys.Backend.API/Controllers/UserController.cs, TheCollabSys.Backend.API/Controllers/WireListController.cs, TheCollabSys.Backend.Entity/DTOs/WireListDTO.cs, TheCollabSys.Backend.Entity/Models/DdWireList.cs
=> The Collabsys - change password feaure for the first time

TheCollabSys.Backend.API/Configuration/InfrastructureServiceInstaller.cs, TheCollabSys.Backend.API/Controllers/ClientsController.cs, TheCollabSys.Backend.API/Controllers/ProjectsController.cs, TheCollabSys.Backend.API/Controllers/StatusController.cs, TheCollabSys.Backend.Data/Interfaces/IStatusRepository.cs, TheCollabSys.Backend.Data/Interfaces/IUnitOfWork.cs, TheCollabSys.Backend.Data/Repositories/StatusRepository.cs, TheCollabSys.Backend.Data/Repositories/UnitOfWork.cs, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/ClientDTO.cs, TheCollabSys.Backend.Entity/DTOs/ProjectSkillDetailDTO.cs, TheCollabSys.Backend.Entity/DTOs/ProjectSkillListDetailDTO.cs, TheCollabSys.Backend.Entity/DTOs/StatusDTO.cs, TheCollabSys.Backend.Entity/Models/DdProject.cs, TheCollabSys.Backend.Entity/Models/DdStatus.cs, TheCollabSys.Backend.Services/ClientService.cs, TheCollabSys.Backend.Services/IProjectService.cs, TheCollabSys.Backend.Services/IStatusService.cs, TheCollabSys.Backend.Services/MappingProfile.cs, TheCollabSys.Backend.Services/ProjectService.cs, TheCollabSys.Backend.Services/ProjectSkillService.cs, TheCollabSys.Backend.Services/StatusService.cs
=> The Collabsys - Projects all in one form

TheCollabSys.Backend.API/Controllers/EngineersController.cs, TheCollabSys.Backend.Data/TheCollabSys.Backend.Data.csproj, TheCollabSys.Backend.Data/TheCollabsysContext.cs, TheCollabSys.Backend.Entity/DTOs/EngineerDTO.cs, TheCollabSys.Backend.Entity/DTOs/EngineerSkillDetailDTO.cs, TheCollabSys.Backend.Entity/DTOs/ProjectDTO.cs, TheCollabSys.Backend.Entity/DTOs/ProjectSkillListDetailDTO.cs, TheCollabSys.Backend.Entity/Models/DdEngineer.cs, TheCollabSys.Backend.Entity/Models/DdProject.cs, TheCollabSys.Backend.Services/EngineerService.cs, TheCollabSys.Backend.Services/EngineerSkillService.cs, TheCollabSys.Backend.Services/IEngineerService.cs, TheCollabSys.Backend.Services/ProjectService.cs
=> The Collabsys - Engineer Form All In One

TheCollabSys.Backend.API/Controllers/EngineersController.cs, TheCollabSys.Backend.API/Controllers/ProjectsController.cs
=> The Collabsys - delete all in one projects and engineers

TheCollabSys.Backend.API/Controllers/DomainController.cs, TheCollabSys.Backend.API/Controllers/InvitationController.cs, TheCollabSys.Backend.API/Controllers/RolesController.cs, TheCollabSys.Backend.Entity/DTOs/InvitationDTO.cs, TheCollabSys.Backend.Entity/DTOs/InvitationModelDTO.cs, TheCollabSys.Backend.Entity/Models/DdInvitation.cs, TheCollabSys.Backend.Services/DomainService.cs, TheCollabSys.Backend.Services/EmployerService.cs, TheCollabSys.Backend.Services/EngineerService.cs, TheCollabSys.Backend.Services/IDomainService.cs, TheCollabSys.Backend.Services/IEmployerService.cs, TheCollabSys.Backend.Services/IInvitationService.cs, TheCollabSys.Backend.Services/IRoleService.cs, TheCollabSys.Backend.Services/InvitationService.cs, TheCollabSys.Backend.Services/RoleService.cs
=> The Collabsys - Invitation module for members

TheCollabSys.Backend.API/Controllers/TokenController.cs, TheCollabSys.Backend.API/Controllers/UserController.cs, TheCollabSys.Backend.API/Controllers/UserRoleController.cs, TheCollabSys.Backend.API/Token/JwtTokenGenerator.cs, TheCollabSys.Backend.Entity/DTOs/UserRoleDTO.cs, TheCollabSys.Backend.Services/IUserRoleService.cs, TheCollabSys.Backend.Services/IUserService.cs, TheCollabSys.Backend.Services/UserRoleService.cs, TheCollabSys.Backend.Services/UserService.cs
=> The Collabsys - User Management CRUD

TheCollabSys.Backend.API/Controllers/EngineersController.cs, TheCollabSys.Backend.API/appsettings.json, TheCollabSys.Backend.Services/EngineerService.cs, TheCollabSys.Backend.Services/IEngineerService.cs
Modified query to filter by email
=> Filter by enginner
